function serompe(){
    return 3 + z
}

try{
    serompe()
}catch(err){
    console.error(err.message)
    console.log("Se ha controlado el error...")
}

